"""add progress to analysis_jobs

Revision ID: 9c2eb372a866
Revises: 6701a427af5e
Create Date: 2026-03-21 00:53:30.882546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2eb372a866'
down_revision: Union[str, Sequence[str], None] = '6701a427af5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('progress', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'progress')
    # ### end Alembic commands ###
