"""remove progress from analysis_jobs

Revision ID: ede80e799cd0
Revises: cc5869f8bb25
Create Date: 2026-03-21 01:31:27.918326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede80e799cd0'
down_revision: Union[str, Sequence[str], None] = 'cc5869f8bb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("SET statement_timeout = '0'")
    op.drop_column('analysis_jobs', 'progress')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('progress', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
